
project:
  type: website

website:
  title: 'Caleb Rother'
  navbar:
    left:
      - href: home.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: Student.qmd
        text: Campus Involvement and Improvement
      - href: CV.qmd
        text: CV
format:
  html:
    theme: cosmo # or: flatly, minty, journal, litera, sketchy, darkly, etc
    css: styles.css

